# Generated by Django 5.2.9 on 2025-12-25 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_securityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username', 'ip_address'], name='incidents_l_usernam_f71238_idx'), models.Index(fields=['locked_until'], name='incidents_l_locked__59bad3_idx')],
            },
        ),
    ]
